# Generated by Django 5.2.6 on 2025-10-19 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], max_length=20, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('solo', 'Solo/Individual'), ('2_10', '2-10 employees'), ('11_50', '11-50 employees'), ('51_200', '51-200 employees'), ('201_1000', '201-1,000 employees'), ('1000_plus', '1,000+ employees')], max_length=20, null=True)),
                ('role', models.CharField(blank=True, choices=[('founder_ceo', 'Founder/CEO'), ('cto_vp_eng', 'CTO/VP Engineering'), ('director', 'Director'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('consultant', 'Consultant'), ('other', 'Other')], max_length=50, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology/Software'), ('finance', 'Finance/Banking'), ('healthcare', 'Healthcare/Medical'), ('ecommerce', 'E-commerce/Retail'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('marketing', 'Marketing/Advertising'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('logistics', 'Logistics/Supply Chain'), ('energy', 'Energy/Utilities'), ('nonprofit', 'Non-profit'), ('government', 'Government'), ('other', 'Other')], max_length=50, null=True)),
                ('services_interested', models.JSONField(default=list, help_text='Multiple services the client is interested in')),
                ('project_goals', models.TextField(help_text='What specific business problem are you trying to solve?')),
                ('current_situation', models.TextField(blank=True, help_text='What tools or systems are you currently using?', null=True)),
                ('budget_range', models.CharField(choices=[('under_10k', 'Under $10K'), ('10k_25k', '$10K-$25K'), ('25k_50k', '$25K-$50K'), ('50k_100k', '$50K-$100K'), ('over_100k', '$100K+'), ('not_determined', 'Not yet determined')], help_text='Estimated project budget', max_length=20)),
                ('timeline', models.CharField(choices=[('immediate', 'Immediate (within 1 month)'), ('1_3_months', '1-3 months'), ('3_6_months', '3-6 months'), ('6_plus_months', '6+ months'), ('exploratory', 'Exploratory')], help_text='When do you need this project completed?', max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High priority'), ('medium', 'Medium priority'), ('low', 'Low priority')], help_text='How critical is this project to your business?', max_length=20, null=True)),
                ('referral_source', models.CharField(blank=True, help_text='How did you hear about my services?', max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('closed_won', 'Closed - Won'), ('closed_lost', 'Closed - Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
