# Generated by Django 5.2.6 on 2025-10-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='referral_source',
            field=models.CharField(default='', help_text='How did you hear about my services?', max_length=200),
        ),
    ]
