# Generated by Django 5.2.6 on 2025-10-05 03:47

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='blog_post_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='blog_post_content_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
