# Generated by Django 5.2.6 on 2025-10-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_blog_post_title_gin_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_slug_cdb902_idx',
        ),
    ]
