# Generated by Django 5.2.6 on 2025-10-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_created_date_author_updated_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
