"""
Django settings for portfolio_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import environ
import boto3
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env()

# Load environment variables from .env file
env_file = os.path.join(BASE_DIR.parent, '.env')
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

# Fetch secrets from AWS Secrets Manager
def get_aws_secrets():
    """Fetch secrets from AWS Secrets Manager"""
    try:
        secret_name = config('SECRET_MANAGER_NAME', default=None)
        region_name = config('AWS_REGION', default='us-east-1')

        if not secret_name:
            return {}

        # Create a Secrets Manager client
        session = boto3.session.Session()
        client = session.client(
            service_name='secretsmanager',
            region_name=region_name
        )

        # Fetch the secret value
        get_secret_value_response = client.get_secret_value(SecretId=secret_name)

        # Parse and return the secret
        if 'SecretString' in get_secret_value_response:
            secret = json.loads(get_secret_value_response['SecretString'])
            return secret
        return {}
    except Exception as e:
        print(f"Error fetching secrets from AWS Secrets Manager: {e}")
        return {}

# Get AWS credentials from Secrets Manager
aws_secrets = get_aws_secrets()

# AWS Configuration
AWS_ACCESS_KEY_ID = aws_secrets.get('AWS_ACCESS_KEY_ID', config('AWS_ACCESS_KEY_ID', default=''))
AWS_SECRET_ACCESS_KEY = aws_secrets.get('AWS_SECRET_ACCESS_KEY', config('AWS_SECRET_ACCESS_KEY', default=''))
AWS_REGION = config('AWS_REGION', default='us-east-1')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-b+_$g1j7-*up%$!z1)&sh0z(h!)h5_*dobu3b2=2#rh6$-=hft')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0').split(',')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'markdownx',
    'django_ses',
    'blog',
    'newsletter',
    'contact',
]

MIDDLEWARE = [
    'portfolio_backend.middleware.HealthCheckMiddleware',  # Health check bypass - must be first
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='portfolio_db'),
        'USER': config('DB_USER', default='portfolio_user'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'connect_timeout': 10,  # 10 second connection timeout to prevent long hangs
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Whitenoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS Settings
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000').split(',')]

CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,https://api.carlosleon.tech').split(',')]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Default page size for all paginated views
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ] if not DEBUG else [],  # Disable throttling in development
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # General API: 100 requests per hour per IP (production only)
        'newsletter_subscribe': '5/hour',  # Newsletter subscription: 5 per hour per IP
        'newsletter_confirm': '10/hour',  # Newsletter confirmation: 10 per hour per IP
        'contact_submit': '3/hour',  # Contact form: 3 submissions per hour per IP
    },
}

# Markdownx Settings
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.fenced_code',
    'markdown.extensions.codehilite',
    'markdown.extensions.tables',
    'markdown.extensions.toc',
]

MARKDOWNX_MARKDOWN_EXTENSION_CONFIGS = {
    'markdown.extensions.codehilite': {
        'css_class': 'highlight',
        'linenums': True,
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration (Amazon SES)
# Use console backend in DEBUG mode for development testing, SES in production
if DEBUG:
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
else:
    EMAIL_BACKEND = config('EMAIL_BACKEND', default='django_ses.SESBackend')

# SES credentials configuration
# Priority: 1) Environment variables, 2) AWS profile (local dev with volume mount)
AWS_SES_ACCESS_KEY_ID = config('AWS_SES_ACCESS_KEY_ID', default=None)
AWS_SES_SECRET_ACCESS_KEY = config('AWS_SES_SECRET_ACCESS_KEY', default=None)

# If no env credentials, try AWS profile (only works with ~/.aws volume mount)
if not AWS_SES_ACCESS_KEY_ID:
    AWS_SES_PROFILE = config('AWS_SES_PROFILE', default=None)
    if AWS_SES_PROFILE:
        try:
            import boto3
            ses_session = boto3.Session(profile_name=AWS_SES_PROFILE)
            ses_credentials = ses_session.get_credentials()
            if ses_credentials:
                AWS_SES_ACCESS_KEY_ID = ses_credentials.access_key
                AWS_SES_SECRET_ACCESS_KEY = ses_credentials.secret_key
        except Exception as e:
            print(f"Warning: Could not load SES credentials from profile '{AWS_SES_PROFILE}': {e}")

# SES configuration
AWS_SES_REGION_NAME = config('AWS_SES_REGION_NAME', default='us-east-2')
AWS_SES_REGION_ENDPOINT = config('AWS_SES_REGION_ENDPOINT', default='email.us-east-2.amazonaws.com')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@carlosleon.tech')
# SES throttling (None = disabled)
AWS_SES_AUTO_THROTTLE = config('AWS_SES_AUTO_THROTTLE', default=None)

# Slack Configuration
SLACK_WEBHOOK_URL = config('SLACK_WEBHOOK_URL', default=None)
